In [1]:
from __future__ import print_function
import torch
import torchvision
import matplotlib.pyplot as plt
import cv2
import numpy as np
import shapely
from shapely.geometry import Polygon,MultiPoint

In [2]:
# get a viusalization 
imgfile = "pcd0100r"
img = plt.imread("{}.png".format(imgfile))

In [3]:
a = np.loadtxt('pcd0100cpos.txt')
boxes = []
box = []
print(a.shape[0])

for i in range(a.shape[0]):
    if i%4 ==0:
        print("Processing %d box" %(i/4+1))
        box = [a[i],a[i+1],a[i+2],a[i+3]]
        box = np.int0(box)
        boxes.append(box)
        print(box)
#print(boxes)

16
Processing 1 box
[[253 319]
 [309 324]
 [307 350]
 [251 345]]
Processing 2 box
[[255 324]
 [308 332]
 [313 295]
 [260 287]]
Processing 3 box
[[260 303]
 [311 309]
 [314 283]
 [263 277]]
Processing 4 box
[[258 279]
 [320 282]
 [321 261]
 [259 258]]


In [ ]:
img = cv2.imread("{}.png".format(imgfile)) 
cv2.namedWindow("Image") 
for eachbox in boxes:
    box = eachbox
    cv2.drawContours(img, [box], 0, (0, 255, 0), 1) 


#cv2.imshow('Image', img)
#cv2.waitKey (0)
cv2.imwrite("test.png", img)
cv2.destroyAllWindows()

In [14]:

poly1 = Polygon(boxes[2]).convex_hull  #四个点顺序为：左上 左下  右下 右上 左上
print(poly1)  

POLYGON ((263 277, 260 303, 311 309, 314 283, 263 277))


In [15]:
poly2 = Polygon(boxes[3]).convex_hull  
print(poly2)  

POLYGON ((259 258, 258 279, 320 282, 321 261, 259 258))


In [16]:
if not poly1.intersects(poly2): #如果两四边形不相交
    iou = 0
else:
    iou = poly1.intersection(poly2).area / poly1.union(poly2).area


In [17]:
iou

0.013999990353766957