In [1]:
from __future__ import print_function
import torch
import torchvision
import matplotlib.pyplot as plt
import cv2
import numpy as np
import shapely
from shapely.geometry import Polygon,MultiPoint
from torchvision import models
import torch.nn as nn

In [2]:
model = models.resnet18(pretrained = False)
fc_features = model.fc.in_features
model.fc = nn.Linear(fc_features,384)

In [3]:
a = np.array([[606, 522,  10,  21, -26],
[606, 522,  10,  21, -26],
             [606, 522,  10,  21, -26],
             [606, 522,  10,  21, -26]])

In [96]:
import numpy as np

cnt = np.array([[1,1],[1,5],[5,5],[5,1]]) # 必须是array数组的形式

rect = cv2.minAreaRect(cnt) # 得到最小外接矩形的（中心(x,y), (宽,高), 旋转角度）

print(rect)

rect1 = ((300.0, 300.0), (200.0, 200.0),60.0)

box = cv2.boxPoints(rect1) # cv2.boxPoints(rect) for OpenCV 3.x 获取最小外接矩形的4个顶点
print(Polygon(box).convex_hull)
print(box)
box = np.int0(box)
print(cv2.minAreaRect(box) )
#cv2.drawContours(img, [box], 0, (0, 0, 255), 2)


((3.0, 3.0), (4.0, 4.0), -90.0)
POLYGON ((336.6025390625 163.3974609375, 163.3974609375 263.3974609375, 263.3974609375 436.6025390625, 436.6025390625 336.6025390625, 336.6025390625 163.3974609375))
[[163.39746 263.39746]
 [336.60254 163.39746]
 [436.60254 336.60254]
 [263.39746 436.60254]]
((299.4999694824219, 299.5), (199.8223876953125, 199.8223876953125), -30.029401779174805)


In [9]:
img = cv2.imread("{}.png".format(14)) 
print(type(img))
print(img.shape)

<class 'numpy.ndarray'>
(1024, 1024, 3)


In [7]:
a = np.array([[606, 522,  10,  21, -26],
[606, 522,  10,  21, -26],
             [606, 522,  10,  21, -26],
             [606, 522,  10,  21, -26]])

In [8]:
a

array([[606, 522,  10,  21, -26],
       [606, 522,  10,  21, -26],
       [606, 522,  10,  21, -26],
       [606, 522,  10,  21, -26]])

In [6]:
int(7.999)

7

In [99]:
x = torch.randn(2, 4, 6)
print(x)

tensor([[[ 0.1765, -1.9168,  1.7381, -1.0750,  1.2845, -1.0576],
         [-0.2025,  0.9610, -1.5827, -1.3296,  1.5626,  2.4105],
         [-1.2492,  0.5375,  1.1566, -0.7512, -2.1055, -0.9719],
         [-0.8304,  0.3109,  0.0688,  0.3912, -1.7305,  2.1093]],

        [[ 0.3666,  1.0640, -1.2060,  0.5374, -0.0543,  0.1310],
         [-1.6427, -1.2656,  0.3952,  0.5391,  0.9398, -1.9632],
         [ 0.7947, -0.9371, -2.2248, -0.9662,  0.2868, -2.6505],
         [ 0.3324, -0.3700, -0.3953,  0.6186, -1.7269, -0.2804]]])


In [100]:
a= torch.split(x,1, dim=2) 
print(a)
a,b,c,d,e,f = a

(tensor([[[ 0.1765],
         [-0.2025],
         [-1.2492],
         [-0.8304]],

        [[ 0.3666],
         [-1.6427],
         [ 0.7947],
         [ 0.3324]]]), tensor([[[-1.9168],
         [ 0.9610],
         [ 0.5375],
         [ 0.3109]],

        [[ 1.0640],
         [-1.2656],
         [-0.9371],
         [-0.3700]]]), tensor([[[ 1.7381],
         [-1.5827],
         [ 1.1566],
         [ 0.0688]],

        [[-1.2060],
         [ 0.3952],
         [-2.2248],
         [-0.3953]]]), tensor([[[-1.0750],
         [-1.3296],
         [-0.7512],
         [ 0.3912]],

        [[ 0.5374],
         [ 0.5391],
         [-0.9662],
         [ 0.6186]]]), tensor([[[ 1.2845],
         [ 1.5626],
         [-2.1055],
         [-1.7305]],

        [[-0.0543],
         [ 0.9398],
         [ 0.2868],
         [-1.7269]]]), tensor([[[-1.0576],
         [ 2.4105],
         [-0.9719],
         [ 2.1093]],

        [[ 0.1310],
         [-1.9632],
         [-2.6505],
         [-0.2804]]]))


In [150]:
x = torch.randn(3, 4, 6)
x

tensor([[[ 0.5643, -0.7426,  0.0868, -0.4582, -1.3775,  2.0045],
         [-1.9216,  0.3849,  0.4712, -0.8824,  0.2958, -0.4918],
         [-0.8246,  1.4874, -0.0049,  0.7959, -0.4344, -0.1679],
         [-1.2201,  0.0290,  1.0291, -0.9009, -1.1445, -0.1303]],

        [[ 0.5058,  1.3449,  0.1524, -1.2777,  1.3667,  0.7691],
         [ 0.7150,  0.6390, -0.4522,  0.9605, -1.6642, -0.0323],
         [-0.9204, -2.0705, -0.6348,  1.8126, -1.0998,  1.0361],
         [-0.4624,  0.6058,  0.1375, -1.2240,  1.4714,  1.4166]],

        [[-0.2585, -1.4957, -0.8655, -1.1410,  0.2746, -0.0361],
         [-0.7117, -0.1402,  0.7039, -2.7702, -0.0539,  1.2939],
         [ 2.5831, -0.3017,  1.2561,  1.2721, -0.3897,  0.3225],
         [ 0.5322,  0.7600, -1.0736,  1.0838, -0.0070, -2.0435]]])

In [151]:
xc = x[:,:,0] 
xc

tensor([[ 0.5643, -1.9216, -0.8246, -1.2201],
        [ 0.5058,  0.7150, -0.9204, -0.4624],
        [-0.2585, -0.7117,  2.5831,  0.5322]])

In [153]:
d = xc>0.4
d = d.float()
print(d)
d*xc

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [0., 0., 1., 1.]])


tensor([[0.5643, -0.0000, -0.0000, -0.0000],
        [0.5058, 0.7150, -0.0000, -0.0000],
        [-0.0000, -0.0000, 2.5831, 0.5322]])

In [63]:
loss_fn = torch.nn.MSELoss(size_average=False)

In [64]:
a=torch.tensor([[1,2,3,4,5,6],[3,4,5,6,7,8]])

b=torch.tensor([[2,3],[4,4]])
loss = loss_fn(a.float(), b.float())

In [65]:
loss

tensor(3.)

In [87]:
a=26

In [88]:
a//8

3

In [89]:
a

26

In [90]:
a-8*(a//8)

2

In [76]:
int(0.9999*8)

7

In [148]:
acc = (2,3,4,5,655,3,21,2)[0]

In [149]:
acc

2